[deps]
BestieTemplate = "e5d671a7-4186-4f1a-bf88-c19b630da94f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
BestieTemplate = {path = ".."}

[compat]
BestieTemplate = "0.17.1"
Documenter = "1"
